x<-0:6
l<-length(x)-1
f<-c(13,25,52,58,32,16,4)
sumfx<-sum(f*x)
sumf<-sum(f)
m<-sumfx/sumf
p<-m/l
pr<-dbinom(x,size=l,p=p)
fe<-pr*sumf
pr<-round(pr,digits=2)
fec<-round(fe,digits=0)
sumfe<-sum(fe)
a<-data.frame(x,f,f*x,pr,fe,fec)
data<-c(NA,sumf,sumfx,NA,NA,sum(fec))
a<-rbind(a,data)
print(a)
c<-chisq.test(f,p=pr)
print(c)