x<-c(1,3,5,7,9)
y<-c(3,5,7,9,11)
xi<-(x+y)/2
f<-c(1,4,6,4,1)
l<-length(x)-1
fx<-f*xi
sumf<-sum(f)
sumfx<-sum(fx)
fxx<-fx*xi
sumfxx<-sum(fxx)
m<-sumfx/sumf
sd<-sqrt((sumfxx/sumf-m*m))
z1<-pnorm(x,m,sd)
z2<-pnorm(y,m,sd)
pr<-z2-z1
fe<-pr*sumf
fee<-round(fe,digits=0)
a<-data.frame(x,y,f,xi,fx,fxx,z1,z2,pr,fe,fee)
s<-c(NA,NA,sumf,NA,sumfx,sumfxx,NA,NA,NA,NA,sum(fee))
a<-rbind(a,s)
print(a)
t<-chisq.test(f,p=pr,rescale.p=T)
print(t)
ta<-qchisq(0.95,df=l)
print(ta)